multiplicador = int(input('Informe um número: '))

produto01 = int(multiplicador * 1)
produto02 = int(multiplicador * 2)
produto03 = int(multiplicador * 3)
produto04 = int(multiplicador * 4)
produto05 = int(multiplicador * 5)
produto06 = int(multiplicador * 6)
produto07 = int(multiplicador * 7)
produto08 = int(multiplicador * 8)
produto09 = int(multiplicador * 9)
produto10 = int(multiplicador * 10)

print('/'*20)
print('{} x {:2} = {}'.format(multiplicador,1, produto01))
print('{} x {:2} = {}'.format(multiplicador,2, produto02))
print('{} x {:2} = {}'.format(multiplicador,3, produto03))
print('{} x {:2} = {}'.format(multiplicador,4, produto04))
print('{} x {:2} = {}'.format(multiplicador,5, produto05))
print('{} x {:2} = {}'.format(multiplicador,6, produto06))
print('{} x {:2} = {}'.format(multiplicador,7, produto07))
print('{} x {:2} = {}'.format(multiplicador,8, produto08))
print('{} x {:2} = {}'.format(multiplicador,9, produto09))
print('{} x {:2} = {}'.format(multiplicador,10, produto10))
#usa o :2 para simular dois digitos 
print('/'*20)